variables:
  adGroup: ''
  ttl: ''

stages:
- stage: WaitForApproval
  jobs:
  - job: WaitForApproval
    pool: server
    steps:
    - checkout: none
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # timeout in 24 hours
      inputs:
        notifyUsers: 'approver@domain.com' 
        instructions: 'Please approve if the user should be added to the group'

- stage: AddUserToGroup
  dependsOn: WaitForApproval
  jobs:
  - job: AddUserToGroup
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $url = "$env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI$env:SYSTEM_TEAMPROJECTID/_apis/build/builds/$($env:BUILD_BUILDID)?api-version=6.0"
          $response = Invoke-RestMethod -Uri $url -Headers @{
            Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
          }
          $requestedBy = $response.requestedBy.displayName
        pwsh: true

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Import-Module ActiveDirectory
          $ttl = New-TimeSpan -Minutes $(ttl)
          Add-ADGroupMember -Identity "$(adGroup)" -Members $requestedBy -MemberTimeToLive $ttl
        pwsh: true
