trigger: none

schedules:
  - cron: "0 0 * * *"  # Runs every day at midnight, adjust as needed
    displayName: Daily midnight Jira task check
    branches:
      include:
      - main
    always: true

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    $this_token = "YourJiraTokenHere"
    $Text = "YourEmailHere:$this_token"
    $Bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
    $EncodedText = [Convert]::ToBase64String($Bytes)

    $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
    $headers.Add("Authorization", "Basic $EncodedText")
    $headers.Add("Content-Type","application/json")
    $this_domain = "YourJiraDomainHere"
    $domain = [System.Uri] "https://$this_domain"

    # Adjust the JQL query to fetch open tasks under the BEG project
    $api_version = 'rest/api/3'
    $endpoint = '/search'
    $data = @"
    {
        "jql" : "project = BEG AND statusCategory != Done",
        "maxResults" : 100
    }
    "@

    $uri = "$($domain)$($api_version)$($endpoint)" 
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls12

    $response = Invoke-RestMethod $uri -Headers $headers -Method 'POST' -Body $data

    foreach ($issue in $response.issues){
        if($issue.fields.summary -like "*ADO Basic*") {
            write-host "Found a match in issue $($issue.key)"
            
            # Set your Azure DevOps parameters here
            $userEmail = "user@example.com" # You may get this from the Jira issue or set a static value
            $orgName = ""

            $uriAzureDevOps = "https://dev.azure.com/$orgName/BuildEngineers/_apis/build/builds?api-version=6.0"
            $bodyAzureDevOps = @{
                "definition" = @{
                    "id" = 1760
                }
                "parameters" = (ConvertTo-Json @{
                    "userEmail" = $userEmail
                    "org" = $orgName
                })
            } | ConvertTo-Json

            $personalAccessToken = "$(AzureManagementPAT)" # from AzureVariables library
            $headersAzureDevOps = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
            $headersAzureDevOps.Add("Authorization", "Basic " + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$personalAccessToken")))
            $headersAzureDevOps.Add("Content-Type","application/json")

            try {
                $responseAzureDevOps = Invoke-RestMethod -Uri $uriAzureDevOps -Method Post -Headers $headersAzureDevOps -Body $bodyAzureDevOps
                write-host "Azure DevOps Pipeline Triggered: $($responseAzureDevOps.id)"
            } catch {
                write-host "Error triggering Azure DevOps Pipeline: $_"
            }
        }
    }
  displayName: 'Query Jira, Check for ADO Basic and Trigger Azure DevOps Pipeline'
